### PR TITLE
Update strings.po

### PR DESCRIPTION
**Pull request by taiseer999**
Updated new strings

### CODE REVIEW

**Comment by icarok99** [comment]
@taiseer999 Resolve the conflict.

**Comment by taiseer999** [comment]
This is a translation of the newly added strings plus a couple of rephrases.

**Comment by icarok99** [comment]
> This is a translation of the newly added strings plus a couple of rephrases.

I know but there was an update and your branch it is with conflict

**Comment by taiseer999** [comment]
I don't know how it happened but it should be alright now.

**Pull request closed without merging**
