### PR TITLE
Translation update (DE)

### PR DESCRIPTION
**Pull request by peat80**

### CODE REVIEW

**Comment by icarok99** [comment]
@peat80 There are conflicts with main branch.

**Comment by icarok99** [comment]
strings.po updated with the new texts from update 0.4.30 https://github.com/icarok99/skin.arctic.fuse/blob/omega/language/resource.language.de_de/strings.po

**Comment by icarok99** [comment]
You have to create a fork of branch omega.

**Comment by icarok99** [comment]
@peat80 Copy this file it has all the texts from today's update. Need to translate into your language.

https://github.com/jurialmunkey/skin.arctic.fuse/blob/2d7adcfd2012ef98466ded90d9c4a2c64b83f87c/language/resource.language.de_de/strings.po

**Comment by peat80** [comment]
I've updated translations, switched branch and made a new pr.

**Comment by icarok99** [comment]
> I've updated translations, switched branch and made a new pr.

Did you copy correctly? Because now there are several " where there shouldn't be
IMG_20231214_091224

IMG_20231214_091339

**Comment by peat80** [comment]
This is added formatting by poedit and makes no difference.
I will NOT do all the work removing this and the next time i open translation file with poedit all will added again.
Looks ugly in a text editor, i know, but huge translation files are way more comfortable to edit wir poedit.

**Comment by peat80** [comment]
Forget about it, i found the settings in poedit to please your eyes @icarok99. ;p

**Comment by icarok99** [comment]
Reason why I leave the text well formatted and so that the translations don't look like that.

IMG_20231214_103028

**Pull request closed without merging**
