### PR TITLE
New mountain images

### PR DESCRIPTION
**Pull request by icarok99**
Mountains (16)

Mountains (17)

### CODE REVIEW

**Comment by jurialmunkey** [comment]
Oh these are nice! 

Where are they from? Or are they AI generated? I need to be careful for licensing if they are someone else's work.

**Comment by icarok99** [comment]
> Oh these are nice!
> 
> Where are they from? Or are they AI generated? I need to be careful for licensing if they are someone else's work.

I found it on this site 

https://www.heroscreen.cc/2023/07/4k-pc-wallpaper-vaporwave-tropical.html?m=1

https://www.heroscreen.cc/2023/07/4k-wallpaper-for-pc-alskan-lanscape.html?m=1

**Comment by icarok99** [comment]
It doesn't show licensability here like the images many different I found.

https://www.google.com/search?q=vaporwave+landscape&tbm=isch&hl=en-US&sa=X&ved=2ahUKEwiOsY346M2DAxUyPLkGHT90CLMQrNwCKAB6BAgBEDs&biw=393&bih=720#imgrc=mb0ZQK4sSrhlaM&imgdii=k7algenq01MNjM

https://www.google.com/search?q=vaporwave+landscape+alaskan&tbm=isch&ved=2ahUKEwiih9u66c2DAxUYNbkGHXOoBfsQ2-cCegQIABAD&oq=vaporwave+landscape+alaskan&gs_lcp=ChJtb2JpbGUtZ3dzLXdpei1pbWcQAzIICAAQgAQQogQyCAgAEIAEEKIEMggIABCABBCiBDoFCAAQgAQ6BggAEAcQHjoECAAQHjoHCAAQgAQQEzoGCAAQHhATOggIABAFEB4QEzoECCEQClDnB1jiF2DXG2gAcAB4AIAB2wGIAfYMkgEFMC42LjOYAQCgAQHAAQE&sclient=mobile-gws-wiz-img&ei=uO6bZaLLHpjq5OUP89CW2A8&bih=672&biw=393&hl=en-US#imgrc=LqO5vqwyoJ2asM

**Comment by icarok99** [comment]
Mountains (18)

**Comment by jurialmunkey** [comment]
I think it should be fine. I can't find any licensing info even with reverse image search. There's no watermark and they look to be AI generated, so it has the impression of a free license. If someone complains I can always switch it back.

I've merged into main branch.

**Pull request closed without merging**
