### PR TITLE
Update FR strings.po

### PR DESCRIPTION
**Pull request by ludovik35**
- Items added by @icarok99 translation
- Minor corrections

### CODE REVIEW

**Comment by icarok99** [comment]
Add to your archive

#: /1080i/Custom_1155_Dialog_SearchDiscover_Year.xml
msgctxt "#31117"
msgid "Lowest"
msgstr ""

#: /1080i/Custom_1155_Dialog_SearchDiscover_Year.xml
msgctxt "#31119"
msgid "Highest"
msgstr ""

**Comment by ludovik35** [comment]
Items added
Thanks

**Comment by icarok99** [comment]
New Items

#: /1080i/Includes_MediaFilter.xml
msgctxt "#31122"
msgid "Watchlist"
msgstr ""

#: /1080i/Includes_MediaFilter.xml
msgctxt "#31123"
msgid "On Deck"
msgstr ""

#: /1080i/Includes_MediaFilter.xml
msgctxt "#31128"
msgid "Trending"
msgstr ""

#: /1080i/Includes_MediaFilter.xml
msgctxt "#31132"
msgid "History"
msgstr ""

#: /1080i/Includes_Views.xml
msgctxt "#31135"
msgid "Page"
msgstr ""

**Review by ludovik35 — COMMENTED** [review]
Resolves https://github.com/jurialmunkey/skin.arctic.fuse/issues/326

**Comment by ludovik35** [comment]
> New Items
> 
> #: /1080i/Includes_MediaFilter.xml msgctxt "#31122" msgid "Watchlist" msgstr ""
> 
> #: /1080i/Includes_MediaFilter.xml msgctxt "#31123" msgid "On Deck" msgstr ""
> 
> #: /1080i/Includes_MediaFilter.xml msgctxt "#31128" msgid "Trending" msgstr ""
> 
> #: /1080i/Includes_MediaFilter.xml msgctxt "#31132" msgid "History" msgstr ""
> 
> #: /1080i/Includes_Views.xml msgctxt "#31135" msgid "Page" msgstr ""

Items translated
Thank you

**Pull request merged**
