### PR TITLE
Update Includes_Images.xml

### PR DESCRIPTION
**Pull request by icarok99**
Before 
Screenshot_2023-12-16-22-32-02-927_org xbmc kodi

After 
Screenshot_2023-12-16-23-14-29-833_org xbmc kodi

### CODE REVIEW

**Comment by jurialmunkey** [comment]
This breaks seekbar status:

Paused video displays as playing:

screenshot00328

**Comment by jurialmunkey** [comment]
Further issues:

Status displays paused video as playing and becomes unclear when episode or chapter name is in header:

screenshot00329

Status displays paused video as playing and becomes unclear when up next obscures the header:

screenshot00330

**Comment by icarok99** [comment]
> Further issues:
> 
> Status displays paused video as playing and becomes unclear when episode or chapter name is in header:
> 
> screenshot00329
> 
> Status displays paused video as playing and becomes unclear when up next obscures the header:
> 
> screenshot00330

I don't think this will be a problem because people used the default skin for a long time, it doesn't even have an indication of when content it is paused or reproducing.
Screenshot_2023-12-17-00-28-58-406_org xbmc kodi

**Comment by icarok99** [comment]
And the way it is now, some people find it confusing.
The reason is "Why would I press the button play on content that is being played?"

**Pull request closed without merging**
