### PR TITLE
Update FR strings.po

### PR DESCRIPTION
**Pull request by ludovik35**
Global FR strings.po update

### CODE REVIEW

**Comment by icarok99** [comment]
Add

#: /1080i/Custom_1181_VideoInfo_Recommendations.xml
msgctxt "#31342"
msgid "More Unavailable"
msgstr ""

#: /1080i/SkinSettings.xml
msgctxt "#31343"
msgid "Disables next widget peek"
msgstr ""

**Comment by ludovik35** [comment]
Added, thanks 😉

**Comment by icarok99** [comment]
#: /1080i/Includes_MediaFilter.xml
msgctxt "#31344"
msgid "Sort letter"
msgstr ""

#: /1080i/Includes_MediaFilter.xml
msgctxt "#31345"
msgid "Direction"
msgstr ""

**Comment by ludovik35** [comment]
Done 😄

**Comment by Bindou01** [comment]
> Global FR strings.po update

Merci beaucoup Ludovic pour l'update Fr. Ca fait plaisir !
Thanks !

**Pull request merged**
