### PR TITLE
Closed for editing 

### PR DESCRIPTION
**Pull request by icarok99**

### CODE REVIEW

**Comment by icarok99** [comment]
From other languages it has been removed "" which was added to more in some texts.

**Comment by jurialmunkey** [comment]
> From other languages it has been removed "" which was added to more in some texts.

This is incorrect.

The quotes are important to the meaning. The text should read:
`Show "More" item on limited widgets`

The "More" item is a specific Kodi item which is shown at the end of a widget list if there are more items in the list than the list can display due to the limit.

It should be in quotes because it is a special item. 
The setting doesn't show `more items on widgets` - it enables **the** `"More" item on widgets` 

image



Also, there is no issue with splitting text strings over multiple lines in a po file. This is done in poedit for readability to avoid extremely long lines. All strings immediately following are joined together when displayed.

**Comment by icarok99** [comment]
The "" I speak of are #: /1080i/Custom_1115_Dialog_Shortcuts.xml
msgctxt "#31525"
msgid ""
"Edit $INFO[Container(22001).ListItem.Label,[LOWERCASE],[/LOWERCASE]] "
"spotlight"

**Comment by icarok99** [comment]
Show More item on limited widgets, Edited and it is as before.

**Comment by icarok99** [comment]
> Show More item on limited widgets, Edited and it is as before.

I did not edit this text in other languages, only of the translation  pt-br

**Pull request closed without merging**
