### PR TITLE
Fix missing timer icon and episode count for Next Episodes/Next Up lists

### PR DESCRIPTION
**Pull request by Jcloak**
I noticed the percentage circle would appear, but the timer icon and unwatched episode counts were still not appearing in the "Next Episodes" list. I noticed the "progress" and "percentage" params are basically the same at this point, so it might be worth consolidating that logic somewhere, but I'll leave that decision up to you.

### CODE REVIEW

**Comment by jurialmunkey** [comment]
This will overlap episode counter. Timer icon should only appear for resumable items.

**Comment by Jcloak** [comment]
Interesting. Right now on my "Next Episodes" list, it just shows a green circle without the timer icon. When I apply my code change, it shows the timer icon as well. Aren't the green percentage circle and timer icon supposed to appear simultaneously?

**Comment by jurialmunkey** [comment]
> Aren't the green percentage circle and timer icon supposed to appear simultaneously?

It depends. There are two different scenarios the percentage circle will show:

1. Item is playable and resumable [elapsed vs total time]
2. Item is an in-progress tvshow [unwatched vs total episode count]

Then a different indicator is shown to differentiate the two:

Timer = Elapsed time
Number = Episode count

> Interesting. Right now on my "Next Episodes" list, it just shows a green circle without the timer icon. When I apply my code change, it shows the timer icon as well.

Depends on what value the addon is setting to the WatchedProgress value.

If resume time, it's because the addon isn't also updating Kodi's internal resume value for the item.
If episode count, then it's because skin isn't showing count for episodes (my fault).

**Comment by jurialmunkey** [comment]
Thinking about it more, the two indicators won't actually end up overlapping because not condition will hide timer when episodes are available.

But there's still a problem with the indicators not lining up if an episode has both states (unwatched episode + resume). In that case, circle would be resume but the indicator will show unwatched count.

Also it's a bit of a heavy condition in it's current state to be evaluate 5 or 6 times per item.

I think probably we can skip considering WatchedEpisodePercent for as that's only relevant for tvshows/seasons. And we can probably also skip PercentPlayed as I think that's only available if IsResumable is also set.

**Comment by jurialmunkey** [comment]
@Jcloak - That change I just pushed above should make it more efficient at least. Can you test and check that it still works for you? I'm not 100% certain about whether or not PercentPlayed still can be set without Kodi setting isResumable.

Not sure how to deal with the indicator mistmatch when both states are true but maybe its not the end of the world -- it just makes it a bit inconsistent. EDIT: I'm going to merge and the deal with mismatch issue later.

**Comment by Jcloak** [comment]
Yes, the changes all look good to me and work as expected. Thanks!

**Comment by jurialmunkey** [comment]
Not sure why I didn't think to do this before. Reordered the percentage variable to put episode progress at top so it will match the indicator order.

Also dropped the percentage param like you suggested and instead consolidated it as  `$PARAM[episode] | $PARAM[progress]` now that we know those conditions work correctly.

Hopefully I haven't broken anything (hurts my head thinking about these conditions!) but I think the logic makes sense and should be a bit cleaner code also.

**Comment by xyzfre** [comment]
Hey @jurialmunkey is this something that could be implemented into AH2 Love the way the percentage progress icons look on Arctic Fuse GREAT WORK

**Comment by jurialmunkey** [comment]
I am not working on AH2. So no, I will not port features.

**Comment by xyzfre** [comment]
@jurialmunkey  After updating last night to v0.4.34 The percentage icon always displays 0% prior to this update, it was displaying the proper number percentage Windows 11 ,Nexus image

**Comment by xyzfre** [comment]
image

**Comment by xyzfre** [comment]
I was loving the way it look with the percentage numbers instead of the circle icon

**Comment by xyzfre** [comment]
My apologies for commenting on this thread,, your in progress TV shows those progress icons work correctlyimage

**Comment by xyzfre** [comment]
> I was loving the way it look with the percentage numbers instead of the circle icon

image

**Comment by xyzfre** [comment]
My apologies for commenting on this thread so much, I updated to Omega Beta 2 and the problem is solved progress icons for Season level and Episode level are working correctly nowimage

**Pull request merged**
