### PR TITLE
Update strings.po

### PR DESCRIPTION
**Pull request by taiseer999**
removed texts [/LOWERCASE]]

### CODE REVIEW

**Comment by jurialmunkey** [comment]
> removed texts [/LOWERCASE]]

Do the lowercase tags cause issues in Arabic? I can try to avoid using them if they are a problem for other languages.

**Comment by icarok99** [comment]
> > removed texts [/LOWERCASE]]
> 
> Do the lowercase tags cause issues in Arabic? I can try to avoid using them if they are a problem for other languages.

That's not it, it's because in 

> > textos removidos [/LOWERCASE]]
> 
> As tags minúsculas causam problemas em árabe? Posso tentar evitar usá-los se forem um problema para outros idiomas.

It's not that.

> > removed texts [/LOWERCASE]]
> 
> Do the lowercase tags cause issues in Arabic? I can try to avoid using them if they are a problem for other languages.

It's not that. Is that some have "" between them

**Comment by icarok99** [comment]
> > removed texts [/LOWERCASE]]
> 
> Do the lowercase tags cause issues in Arabic? I can try to avoid using them if they are a problem for other languages.

It's not that. Is that some had "" between them.

**Comment by taiseer999** [comment]
No not really I normally upload the file after testing it and it’s never caused any issues

**Comment by taiseer999** [comment]
PS
The update contains all the new commits as of yesterday

**Comment by icarok99** [comment]
> PS The update contains all the new commits as of yesterday

I just did this a few minutes ago.

**Comment by icarok99** [comment]
@taiseer999 I need your help translating an add-on.

https://github.com/icarok99/Otaku/tree/New-languages

**Comment by taiseer999** [comment]
I will take a look at it tonight

**Pull request closed without merging**
