### PR TITLE
Update strings.po

### PR DESCRIPTION
**Pull request by taiseer999**
improvement on ar v0.4.30

### CODE REVIEW

**Comment by icarok99** [comment]
This translation was merged into my pull request.

**Comment by jurialmunkey** [comment]
> This translation was merged into my pull request.

@icarok99 - There's a few extra translations see:
https://github.com/jurialmunkey/skin.arctic.fuse/pull/295/files

Easy for me to resolve conflict and merge now.

**Comment by icarok99** [comment]
> > Esta tradução foi mesclada em minha solicitação pull.
> 
> @icarok99- Existem algumas traduções extras, consulte: https://github.com/jurialmunkey/skin.arctic.fuse/pull/295/files
> 
> É fácil para mim resolver conflitos e mesclar agora.

I have added.

**Comment by icarok99** [comment]
In my pull request I had even corrected texts like this 
IMG_20231213_221505

**Comment by icarok99** [comment]
And there are also extra translations.

**Comment by icarok99** [comment]
> > This translation was merged into my pull request.
> 
> @icarok99 - There's a few extra translations see: https://github.com/jurialmunkey/skin.arctic.fuse/pull/295/files
> 
> Easy for me to resolve conflict and merge now.

@jurialmunkey I added extra translations

https://github.com/icarok99/skin.arctic.fuse/blob/omega/language/resource.language.ar_sa/strings.po

**Pull request merged**
