### PR TITLE
Update strings.po

### PR DESCRIPTION
**Pull request by dm1tz**
Includes changes from f25d1ee

### CODE REVIEW

**Comment by dm1tz** [comment]
Sorry @icarok99, haven't seen #332. But, I did include all of your changes.

**Comment by dm1tz** [comment]
Alright, seems like all of the translations are up to date and even. The only exception being ar_sa with 1957 lines, but there are a lot of multiline msgstrs.
```
1899 ./resource.language.zh_cn/strings.po
1899 ./resource.language.fr_fr/strings.po
1899 ./resource.language.uk_ua/strings.po
1899 ./resource.language.it_it/strings.po
1899 ./resource.language.pt_br/strings.po
1957 ./resource.language.ar_sa/strings.po
1899 ./resource.language.de_de/strings.po
1899 ./resource.language.en_gb/strings.po
```

**Comment by icarok99** [comment]
> Alright, seems like all of the translations are up to date and even. The only exception being ar_sa with 1957 lines, but there are a lot of multiline msgstrs.
> 
> ```
> 1899 ./resource.language.zh_cn/strings.po
> 1899 ./resource.language.fr_fr/strings.po
> 1899 ./resource.language.uk_ua/strings.po
> 1899 ./resource.language.it_it/strings.po
> 1899 ./resource.language.pt_br/strings.po
> 1957 ./resource.language.ar_sa/strings.po
> 1899 ./resource.language.de_de/strings.po
> 1899 ./resource.language.en_gb/strings.po
> ```

I reduce to 1901 https://github.com/icarok99/skin.arctic.fuse/blob/Omega-2/language/resource.language.ar_sa/strings.po

**Comment by dm1tz** [comment]
> I reduce to 1901 https://github.com/icarok99/skin.arctic.fuse/blob/Omega-2/language/resource.language.ar_sa/strings.po

Thanks, included that.

@jurialmunkey FYI, this PR includes all of the remaining translation pull requests (#334, #330, #321) so I think it'll be better to merge this instead of resolving conflicts with the remaining ones.

Update on line count: 
```
1899 ./resource.language.zh_cn/strings.po
1899 ./resource.language.fr_fr/strings.po
1899 ./resource.language.uk_ua/strings.po
1899 ./resource.language.it_it/strings.po
1899 ./resource.language.pt_br/strings.po
1900 ./resource.language.ar_sa/strings.po
1899 ./resource.language.de_de/strings.po
1899 ./resource.language.en_gb/strings.po
```

**Comment by ludovik35** [comment]
@dm1tz it seems to be OK for you to take PR off other maintainer to make it yours without any contact, quote or thanks (second time for me).
I'm convinced that it's very important and useful to cooperate with other but I'm note sure that's what you're doing.

**Comment by dm1tz** [comment]
> @dm1tz it seems to be OK for you to take PR off other maintainer to make it yours without any contact, quote or thanks (second time for me). I'm convinced that it's very important and useful to cooperate with other but I'm note sure that's what you're doing.

Sorry to hear that, I did not mean to offend you in any way. I'm just trying to ease the burden of merging conflicting files. I will mention all of the translators in the commit message. Besides, if this is that important to you, you should probably include yourself as a translator in the .po file.

**Comment by ludovik35** [comment]
@dm1tz thanks for your quote in your PR.

Don't misinterpret what I've written.

There's no intellectual property problem (I don't own anything on this repo) or reward problem (I'm not looking for a medal). 
Like you, I'm simply trying to contribute to an extension I like and support a developer who deserves it (@jurialmunkey )

What I'm saying is that taking the sometimes long and tedious work of several people within an open PR and adding a few lines to it and re-launching it within another PR doesn't seem the best idea and not the most efficient (risk of creating conflict). 

To really cooperate together, the best practice seems to me to be to start by looking to for if a PR is in progress on a language and to help out on that one. This seems to me more efficient (no conflict between PR) and more satisfying for everyone (because of the teamwork involved). 

The door is open to all PR that I may have initiated, and good will is welcome.

**Pull request closed without merging**
